### ISSUE TITLE
OCD / inconvenience

### ISSUE THREAD

**Issue by alcohol** [domcode/rafflers#153]
The OCD kid in me would really prefer to see the directories named in the form of `<language>-<author>` or `<language>-<variation>-<author>`, and not vice versa as it is now. I'm more interested in quickly figuring out if a language is already present or not in the list. What are your thoughts on this?

**Comment by lucasvanlierop** [comment]
I'm having the same thoughts for some time, @rosstuck what do you think?

**Comment by lucasvanlierop** [comment]
ping @rosstuck :-P

**Comment by rosstuck** [comment]
Totally in favor :)

**Comment by lucasvanlierop** [comment]
![chaos](http://s2.quickmeme.com/img/f9/f959e67bdd7801b9575f7c506c5f95145fe31cbb7ecb6e2fde05501cd46f4f40.jpg)

**Comment by lucasvanlierop** [comment]
Fixed by #162
