### ISSUE TITLE
Ruby client

### ISSUE THREAD

**Issue by Stelian** [domcode/rafflers#2]
As far as I've seen there is only a php and a python client but no ruby. Can we have a ruby client please?

**Comment by simicic** [comment]
Will come! ;) Now, let's see who makes it first!

**Comment by rosstuck** [comment]
![popcorn](http://img2.wikia.nocookie.net/__cb20140927224455/disney/images/9/98/Popcorn.gif)

Stelian's got 6 hours of meetings today, so advantage is yours, @simicic!

**Comment by Stelian** [comment]
@simicic you have a small heads up, but the war ain't over!

**Comment by simicic** [comment]
haha, then the good news can be that I work as well, maybe someone else can come in!
![](http://reactiongif.org/wp-content/uploads/GIF/2014/08/GIF-Amused-funny-jaw-drop-LOL-Newman-OMG-Seinfeld-shocked-surprised-GIF_1.gif)

**Comment by rosstuck** [comment]
There's no rule that says we can't have multiple rafflers in the same language. That would even be fun.

There's also no rule that says a dog can't play basketball. 
![air bud](http://media.giphy.com/media/7u8SK4p1Cny2Q/giphy.gif)

**Comment by janpaul** [comment]
```ruby
File.readlines($1).sample
```

**Comment by rosstuck** [comment]
![whaaa](http://i.imgur.com/VQLGJOL.gif)

Seriously though, PR? :) And then no more GIFs for me today, I promise.

**Comment by janpaul** [comment]
I will leave that for @simicic . She probably wants to write a spec too ;-)

![](https://geekmeat.slack.com/files/janbroeze/F03FUARF3/ofrmwr4zn4vjabzbakgn.jpg)

**Comment by simicic** [comment]
haha, @janpaul  believe it or not, that was my first thought, there should be some tests!! :smile:

**Comment by janpaul** [comment]
@simicic oh I absolutely believe it! I've known you a bit longer than today ;-)

**Comment by janpaul** [comment]
```ruby
File.readlines($1).sample if $1 && File.exists?($1)
```

**Comment by simicic** [comment]
oh no! where are the tests @Stelian ?? :smile:

**Comment by Stelian** [comment]
I just ... /me walks away

**Comment by janpaul** [comment]
@simicic another oneliner for you then
```ruby
describe Raffle do
  let(:raffle) { Raffle.new } 
  it 'should be something sensible' do
    allow(File).to receive(:readlines).and_return %w(foobar)
    expect(raffle.run).to eq 'foobar'
  end
```

**Comment by simicic** [comment]
I am sorry @janpaul but this does not guarantee randomness, foobar could be my name ;)
you forgot one `should have_received :sample` ;)

**Comment by janpaul** [comment]
@simicic pffft

**Comment by rosstuck** [comment]
Reopening until we have a Ruby raffler with raffler with _drama_!

**Comment by ramondelafuente** [comment]
I wonder if I should try... does Ruby have any functions that start with "array_" ?
