### ISSUE TITLE
I'm really disappointed

### ISSUE THREAD

**Issue by fideloper** [domcode/rafflers#27]
...that the "java" raffler is only one class.

Hardly Enterprise™, y'all.

We can do better.

![image](https://cloud.githubusercontent.com/assets/467411/5946254/ee6b25c2-a6f9-11e4-801f-a705e00d515e.png)

**Comment by rosstuck** [comment]
Assigning @jeroenvdgulik.

**Comment by lucasvanlierop** [comment]
https://github.com/domcode/rafflers/tree/master/bkors-java-spring-boot-enterprice
